// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey',
    appId: '1:123456789:web:demo',
    messagingSenderId: '123456789',
    projectId: 'urban-wildlife-tracker-demo',
    authDomain: 'urban-wildlife-tracker-demo.firebaseapp.com',
    storageBucket: 'urban-wildlife-tracker-demo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4GIcehy0ROdOQm6f6e6BO7WWhxMQZRTc',
    appId: '1:68631477722:android:3c2102c8422507c43614e3',
    messagingSenderId: '68631477722',
    projectId: 'urban-wildlife-tracker',
    storageBucket: 'urban-wildlife-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey',
    appId: '1:123456789:ios:demo',
    messagingSenderId: '123456789',
    projectId: 'urban-wildlife-tracker-demo',
    storageBucket: 'urban-wildlife-tracker-demo.firebasestorage.app',
    iosBundleId: 'com.example.urbanWildlifeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey',
    appId: '1:123456789:macos:demo',
    messagingSenderId: '123456789',
    projectId: 'urban-wildlife-tracker-demo',
    storageBucket: 'urban-wildlife-tracker-demo.firebasestorage.app',
    iosBundleId: 'com.example.urbanWildlifeTracker',
  );
}
